import type { TemplateId } from '../types';
import { grid } from './grid';

const sprite = (block: string): readonly string[] => grid(16, 16, block);

export const TEMPLATES: Record<TemplateId, readonly string[]> = {
    beast: sprite(`
        ................
        .....x....x.....
        ....xbx..xbx....
        ....xbbbbbbx....
        ...xxbbbbbbxx...
        ..xbbbeebbeeex..
        ..xbbbppbppbbx..
        ..xbbbaaaabbbx..
        ...xbbbbbbbbx...
        ....xbbbbbbx....
        ...xxbxxbxxx....
        ..xbbx..xbbx....
        ..xbx....xbx....
        ..xx......xx....
        ................
        ................
    `),
    brute: sprite(`
        ...a........a...
        ..xax..xx..xax..
        ....xbbbbbbx....
        ...xxbbbbbbxx...
        ..xbbbeebbeeex..
        ..xbbbppbppbbx..
        ..xbbbbbbbbbbx..
        ...xbbaaaabbx...
        ....xbbbbbbx....
        ...xxbxxbxxx....
        ..xbbx..xbbx....
        ..xbx....xbx....
        ..xx......xx....
        ................
        ................
        ................
    `),
    avian: sprite(`
        ................
        ....xx....xx....
        ...xbbx..xbbx...
        ..xbbbbxxbbbbx..
        ..xbeeebbbeebx..
        .xxbpppbbpppxx..
        .xbbbbbbbbbbbbx.
        ..xbbbaaaabbbx..
        ...xxbbbbbbxx...
        .....xbbbbx.....
        ....xxbxxbxx....
        ....xbx..xbx....
        ....xx....xx....
        ................
        ................
        ................
    `),
    blob: sprite(`
        ................
        ................
        ....xxxxxxxx....
        ...xbbbbbbbbx...
        ..xbbbbbbbbbbx..
        ..xbeebbbbbeex..
        ..xbppbbbbppbx..
        ..xbbbbbbbbbbx..
        ..xbbbaaaabbbx..
        ...xbbbbbbbbx...
        ....xbbbbbbx....
        .....xxbbxx.....
        ......x..x......
        .....xx..xx.....
        ................
        ................
    `),
    serpent: sprite(`
        ................
        .......xxx......
        .....xxbbbxx....
        ....xbbbbbbbx...
        ...xbbbeebbbx...
        ..xxbbbppbbbxx..
        .xbbbbbbbbbbbbx.
        .xbbaaaaaaaaaax.
        ..xbbbbbbbbbbx..
        ...xxbbbbbbxx...
        .....xbbbbx.....
        ....xxbbbxx.....
        ....xbbbbbx.....
        .....xxxxx......
        ................
        ................
    `),
    armor: sprite(`
        ................
        .....xxxxxx.....
        ....xaaaaaax....
        ...xaaddddaxx...
        ..xaaaadadaaax..
        ..xaddeeedeedx..
        ..xaddppdppddx..
        ..xadddddddddx..
        ...xaaaaxaaax...
        ....xbbbbbbx....
        ...xxbxxxxbxx...
        ...xbbx..xbbx...
        ...xbx....xbx...
        ...xx......xx...
        ................
        ................
    `),
    dragon: sprite(`
        ..x..........x..
        ..ax........xa..
        .xaxx......xxax.
        .xaaxxxxxxxxaax.
        ..xbbbbbbbbbbx..
        ..xbeebbbbbeeex.
        ..xbppbbbbpppxx.
        ..xbbbbbbbbbbbx.
        ...xbbbaaaabbx..
        ....xbbbbbbbx...
        ...xxbxxxxbxx...
        ..xaax....xaax..
        ..xax......xax..
        ...x........x...
        ................
        ................
    `),
};

/** Hand-drawn starters, shown instead of the shared template. */
export const FRONTS: Record<string, readonly string[]> = {
    voltik: sprite(`
        ................
        .....x....x.....
        ....xbx..xbx....
        ....xbbbbbbx....
        ...xxbbbbbbxx...
        ..xbbbeebbeeex..
        ..xbbbppbppbbx..
        ..xbbbaaaabbbx..
        ...xbbbbbbbbx...
        ....xbbbbbbx....
        ...xxbxxbxxx....
        ..xbbx..xbbx....
        ..xbx....xbx....
        ..xx.....xxx....
        ........xax.....
        .......xaax.....
    `),
    bunkle: sprite(`
        ................
        ....xxxxxxxx....
        ...xaaddddaxx...
        ..xaaddddddaax..
        ..xaddddddddax..
        ..xaddeeedeedx..
        ..xaddppdppddx..
        ..xadddddddddx..
        ..xaaddddddaax..
        ...xaaaaxaaax...
        ....xxxxxxxx....
        ...xxbxxxxbxx...
        ...xbbx..xbbx...
        ...xbx....xbx...
        ...xx......xx...
        ................
    `),
    flaren: sprite(`
        .x..........x...
        xax........xax..
        .xaxx....xxax...
        ..xbbbbbbbbx....
        ..xbeeebbeeex...
        ..xbpppbbpppx...
        ...xbbbbbbbbx...
        ....xbbbabbbx...
        .....xbbbbbx....
        ....xxbxxbxx....
        ...xbbx..xbbx...
        ...xbx....xbxx..
        ...xx.....xaxx..
        ..........xaax..
        .........xaxx...
        ..........xx....
    `),
};

/** Back view used for the player's fighter. */
export const BACKS: Record<string, readonly string[]> = {
    voltik: sprite(`
        ................
        .....x....x.....
        ....xbx..xbx....
        ....xbbbbbbx....
        ...xxbbbbbbxx...
        ..xbbbbbbbbbbx..
        ..xbbbbbbbbbbx..
        ..xbbbbbbbbbbx..
        ...xbbbbbbbbx...
        ....xbbbbbbx....
        ...xxbxxbxxx....
        ..xbbx..xbbx....
        ..xbx....xbx....
        ..xx......xx....
        ........xax.....
        .......xaax.....
    `),
    bunkle: sprite(`
        ................
        ....xxxxxxxx....
        ...xddddddddx...
        ..xddaaaaaaddx..
        ..xddaaaaaaddx..
        ..xddaaaaaaddx..
        ..xddaaaaaaddx..
        ..xddaaaaaaddx..
        ..xddddddddddx..
        ...xxxxxxxxxx...
        ....xxxxxxxx....
        ...xx......xx...
        ...xb......bx...
        ...xb......bx...
        ...xx......xx...
        ................
    `),
    flaren: sprite(`
        ..x..........x..
        .xax........xax.
        ..xaxx....xxax..
        ...xbbbbbbbbx...
        ..xbbbbbbbbbbx..
        ..xbbbbbbbbbbx..
        ..xbbbbbbbbbbx..
        ...xbbbbbbbbx...
        ....xbbbbbbx....
        ....xxbxxbxx....
        ...xbbx..xbbx...
        ...xbx....xbx...
        ...xx......xax..
        ...........xaax.
        ..........xaxx..
        ...........xx...
    `),
};

export const SEAL: readonly string[] = sprite(`
    ................
    ......xxxx......
    ....xxbbbbxx....
    ...xbbbbbbbbx...
    ..xbbbbbbbbbbx..
    ..xbbbbbbbbbbx..
    .xxxxxxxxxxxxxx.
    .xeeeeeeeeeeeex.
    ..xeeeeeeeeeeex.
    ..xeeeexxxeeeex.
    ...xeeexxeeeex..
    ....xeeeeeeex...
    .....xeeeeex....
    ......xxxx......
    ................
    ................
`);
